[[redirects]]
from = "/episodes/0"
to = "/podcast/episode/00-developer-fangen-bei-0-an-zu-zählen?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/1"
to = "/podcast/episode/01-side-projects-fluch-oder-segen-für-die-karriere?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/2"
to = "/podcast/episode/02-technologienzoo-side-projects?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/3"
to = "/podcast/episode/03-over-engineering-das-werkzeug-des-teufels?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/4"
to = "podcast/episode/04-lohnt-der-einstieg-in-open-source?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/5"
to = "/podcast/episode/05-team-lead-der-einzige-ausweg?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/6"
to = "/podcast/episode/06-hype-oder-hope-job-titel-und-beförderungen?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/7"
to = "/podcast/episode/07-die-freelance-freiheit?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/8"
to = "/podcast/episode/08-vergiss-doch-datenbanken?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/9"
to = "/podcast/episode/09-ukraine?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/10"
to = "/podcast/episode/10-das-karriere-booster-meeting-11s?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/11"
to = "/podcast/episode/11-die-suche-nach-dem-it-traumjob?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/12"
to = "/podcast/episode/12-make-oder-buy?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/13"
to = "/podcast/episode/13-produktivität?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/14"
to = "/podcast/episode/14-async-und-await-asynchrones-arbeiten-im-alltag?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/15"
to = "/podcast/episode/15-source-code-kommentare-git-commits-messages-merge-commits-und-branch-visualisierungs-kunst?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/16"
to = "/podcast/episode/16-code-reviews-nützlich-oder-bremsen-nur-ein-gutes-team?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/17"
to = "/podcast/episode/17-was-können-wir-beim-incident-management-von-der-feuerwehr-lernen?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/18"
to = "/podcast/episode/18-ziele-und-performance-metriken-für-teams-und-mich-selbst?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/19"
to = "/podcast/episode/19-datenbank-deepdive-oder-das-ende-einer-ära-von-redis-bis-clickhouse?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/20"
to = "/podcast/episode/20-off-boarding-und-on-boarding-wie-verlasse-ich-eine-firma-richtig?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/21"
to = "/podcast/episode/21-static-site-generators-die-webseite?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/22"
to = "/podcast/episode/22-nosql-acid-base-ende-einer-ära-teil-2?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/23"
to = "/podcast/episode/23-schaltest-du-noch-oder-automatisiert-du-schon-home-automation?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/24"
to = "/podcast/episode/24-infrastructure-as-code-oder-old-man-yells-at-cloud?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/podcast/rss"
to = "https://feeds.redcircle.com/0ecfdfd7-fda1-4c3d-9515-476727f9df5e"
status = 302
force = true

[[redirects]]
from = "/episodes/25"
to = "/podcast/episode/25-tech-entlassungswellen-job-interview-skills?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/26"
to = "/podcast/episode/26-my-english-is-not-the-yellow-from-the-egg-arbeiten-in-internationalen-teams?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/27"
to = "/podcast/episode/27-sicherheit-in-der-dependency-hölle?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/28"
to = "/podcast/episode/28-o1-olog-n-on2-ist-die-komplexität-von-algorithmen-im-entwickler-alltag-relevant?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/29"
to = "/podcast/episode/29-die-andere-seite-meetups-konferenzen-organisieren?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/30"
to = "/podcast/episode/30-ist-ein-informatikstudium-sinnvoll-welche-ausbildung-für-devs?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/31"
to = "/podcast/episode/31-ich-automatisiere-mir-die-welt-wie-sie-mir-gefällt-mit-github-actions?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/32"
to = "/podcast/episode/32-die-richtigen-leute-anstellen-die-recruiting-pipeline?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/33"
to = "/podcast/episode/33-andy-im-team-lead-bewerbungsgespräch?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/34"
to = "/podcast/episode/34-wie-cloudy-bist-du?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/35"
to = "/podcast/episode/35-knowledge-sharing-oder-die-person-die-nie-gehen-sollte?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/36"
to = "/podcast/episode/36-sechs-stellige-it-gehälter-wie-was-wo-fair?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/37"
to = "/podcast/episode/37-mit-it-büchern-geld-verdienen-wer-liest-überhaupt-noch-bücher?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/38"
to = "/podcast/episode/38-monitoring-metriken-tracing-alerting-observability?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/39"
to = "/podcast/episode/39-gemischte-tüte-software-engineer-github-opensource-git-und-homeoffice?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/40"
to = "/podcast/episode/40-wie-wird-man-und-frau-zum-senior-dev?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep0"
to = "/podcast/episode/00-developer-fangen-bei-0-an-zu-zählen"
status = 301
force = true

[[redirects]]
from = "/ep1"
to = "/podcast/episode/01-side-projects-fluch-oder-segen-für-die-karriere"
status = 301
force = true

[[redirects]]
from = "/ep2"
to = "/podcast/episode/02-technologienzoo-side-projects"
status = 301
force = true

[[redirects]]
from = "/ep3"
to = "/podcast/episode/03-over-engineering-das-werkzeug-des-teufels"
status = 301
force = true

[[redirects]]
from = "/ep4"
to = "podcast/episode/04-lohnt-der-einstieg-in-open-source"
status = 301
force = true

[[redirects]]
from = "/ep5"
to = "/podcast/episode/05-team-lead-der-einzige-ausweg"
status = 301
force = true

[[redirects]]
from = "/ep6"
to = "/podcast/episode/06-hype-oder-hope-job-titel-und-beförderungen"
status = 301
force = true

[[redirects]]
from = "/ep7"
to = "/podcast/episode/07-die-freelance-freiheit"
status = 301
force = true

[[redirects]]
from = "/ep8"
to = "/podcast/episode/08-vergiss-doch-datenbanken"
status = 301
force = true

[[redirects]]
from = "/ep9"
to = "/podcast/episode/09-ukraine"
status = 301
force = true

[[redirects]]
from = "/ep10"
to = "/podcast/episode/10-das-karriere-booster-meeting-11s"
status = 301
force = true

[[redirects]]
from = "/ep11"
to = "/podcast/episode/11-die-suche-nach-dem-it-traumjob"
status = 301
force = true

[[redirects]]
from = "/ep12"
to = "/podcast/episode/12-make-oder-buy"
status = 301
force = true

[[redirects]]
from = "/ep13"
to = "/podcast/episode/13-produktivität"
status = 301
force = true

[[redirects]]
from = "/ep14"
to = "/podcast/episode/14-async-und-await-asynchrones-arbeiten-im-alltag"
status = 301
force = true

[[redirects]]
from = "/ep15"
to = "/podcast/episode/15-source-code-kommentare-git-commits-messages-merge-commits-und-branch-visualisierungs-kunst"
status = 301
force = true

[[redirects]]
from = "/ep16"
to = "/podcast/episode/16-code-reviews-nützlich-oder-bremsen-nur-ein-gutes-team"
status = 301
force = true

[[redirects]]
from = "/ep17"
to = "/podcast/episode/17-was-können-wir-beim-incident-management-von-der-feuerwehr-lernen"
status = 301
force = true

[[redirects]]
from = "/ep18"
to = "/podcast/episode/18-ziele-und-performance-metriken-für-teams-und-mich-selbst"
status = 301
force = true

[[redirects]]
from = "/ep19"
to = "/podcast/episode/19-datenbank-deepdive-oder-das-ende-einer-ära-von-redis-bis-clickhouse"
status = 301
force = true

[[redirects]]
from = "/ep20"
to = "/podcast/episode/20-off-boarding-und-on-boarding-wie-verlasse-ich-eine-firma-richtig"
status = 301
force = true

[[redirects]]
from = "/ep21"
to = "/podcast/episode/21-static-site-generators-die-webseite"
status = 301
force = true

[[redirects]]
from = "/ep22"
to = "/podcast/episode/22-nosql-acid-base-ende-einer-ära-teil-2"
status = 301
force = true

[[redirects]]
from = "/ep23"
to = "/podcast/episode/23-schaltest-du-noch-oder-automatisiert-du-schon-home-automation"
status = 301
force = true

[[redirects]]
from = "/ep24"
to = "/podcast/episode/24-infrastructure-as-code-oder-old-man-yells-at-cloud"
status = 301
force = true

[[redirects]]
from = "/podcast/rss"
to = "https://feeds.redcircle.com/0ecfdfd7-fda1-4c3d-9515-476727f9df5e"
status = 302
force = true

[[redirects]]
from = "/ep25"
to = "/podcast/episode/25-tech-entlassungswellen-job-interview-skills"
status = 301
force = true

[[redirects]]
from = "/ep26"
to = "/podcast/episode/26-my-english-is-not-the-yellow-from-the-egg-arbeiten-in-internationalen-teams"
status = 301
force = true

[[redirects]]
from = "/ep27"
to = "/podcast/episode/27-sicherheit-in-der-dependency-hölle"
status = 301
force = true

[[redirects]]
from = "/ep28"
to = "/podcast/episode/28-o1-olog-n-on2-ist-die-komplexität-von-algorithmen-im-entwickler-alltag-relevant"
status = 301
force = true

[[redirects]]
from = "/ep29"
to = "/podcast/episode/29-die-andere-seite-meetups-konferenzen-organisieren"
status = 301
force = true

[[redirects]]
from = "/ep30"
to = "/podcast/episode/30-ist-ein-informatikstudium-sinnvoll-welche-ausbildung-für-devs"
status = 301
force = true

[[redirects]]
from = "/ep31"
to = "/podcast/episode/31-ich-automatisiere-mir-die-welt-wie-sie-mir-gefällt-mit-github-actions"
status = 301
force = true

[[redirects]]
from = "/ep32"
to = "/podcast/episode/32-die-richtigen-leute-anstellen-die-recruiting-pipeline"
status = 301
force = true

[[redirects]]
from = "/ep33"
to = "/podcast/episode/33-andy-im-team-lead-bewerbungsgespräch"
status = 301
force = true

[[redirects]]
from = "/ep34"
to = "/podcast/episode/34-wie-cloudy-bist-du"
status = 301
force = true

[[redirects]]
from = "/ep35"
to = "/podcast/episode/35-knowledge-sharing-oder-die-person-die-nie-gehen-sollte"
status = 301
force = true

[[redirects]]
from = "/ep36"
to = "/podcast/episode/36-sechs-stellige-it-gehälter-wie-was-wo-fair"
status = 301
force = true

[[redirects]]
from = "/ep37"
to = "/podcast/episode/37-mit-it-büchern-geld-verdienen-wer-liest-überhaupt-noch-bücher"
status = 301
force = true

[[redirects]]
from = "/ep38"
to = "/podcast/episode/38-monitoring-metriken-tracing-alerting-observability"
status = 301
force = true

[[redirects]]
from = "/ep39"
to = "/podcast/episode/39-gemischte-tüte-software-engineer-github-opensource-git-und-homeoffice"
status = 301
force = true

[[redirects]]
from = "/ep40"
to = "/podcast/episode/40-wie-wird-man-und-frau-zum-senior-dev"
status = 301
force = true

[[redirects]]
from = "/episodes/41"
to = "/podcast/episode/41-sql-injections-ein-unterschätztes-risiko?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep41"
to = "/podcast/episode/41-sql-injections-ein-unterschätztes-risiko"
status = 301
force = true

[[redirects]]
from = "/episodes/42"
to = "/podcast/episode/42-lexer-parser-und-open-source-in-counterstrike?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep42"
to = "/podcast/episode/42-lexer-parser-und-open-source-in-counterstrike"
status = 301
force = true

[[redirects]]
from = "/episodes/43"
to = "/podcast/episode/43-cloud-vs-on-premise-die-entscheidungshilfe?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep43"
to = "/podcast/episode/43-cloud-vs-on-premise-die-entscheidungshilfe"
status = 301
force = true

[[redirects]]
from = "/episodes/44"
to = "/podcast/episode/44-der-weg-zum-hochperformanten-team?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep44"
to = "/podcast/episode/44-der-weg-zum-hochperformanten-team"
status = 301
force = true

[[redirects]]
from = "/episodes/45"
to = "/podcast/episode/45-datengetriebene-entscheidungen-und-der-perfekte-dashboard-stack?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep45"
to = "/podcast/episode/45-datengetriebene-entscheidungen-und-der-perfekte-dashboard-stack"
status = 301
force = true

[[redirects]]
from = "/episodes/46"
to = "/podcast/episode/46-welches-problem-löst-docker?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep46"
to = "/podcast/episode/46-welches-problem-löst-docker"
status = 301
force = true

[[redirects]]
from = "/episodes/47"
to = "/podcast/episode/47-wer-visionen-hat-soll-zum-arzt?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep47"
to = "/podcast/episode/47-wer-visionen-hat-soll-zum-arzt"
status = 301
force = true

[[redirects]]
from = "/episodes/48"
to = "/podcast/episode/48-der-layer-unter-docker-containerd-kubernetes-container-runtime-interface-cri-o-und-open-container-initiative-oci?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep48"
to = "/podcast/episode/48-der-layer-unter-docker-containerd-kubernetes-container-runtime-interface-cri-o-und-open-container-initiative-oci"
status = 301
force = true

[[redirects]]
from = "/episodes/49"
to = "/podcast/episode/49-die-zukunft-software-repository-mining?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep49"
to = "/podcast/episode/49-die-zukunft-software-repository-mining"
status = 301
force = true

[[redirects]]
from = "/episodes/50"
to = "/podcast/episode/50-dei-erhöht-innovation-und-den-finanziellen-erfolg?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep50"
to = "/podcast/episode/50-dei-erhöht-innovation-und-den-finanziellen-erfolg"
status = 301
force = true

[[redirects]]
from = "/episodes/51"
to = "/podcast/episode/51-was-ist-das-staff-engineer-level?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep51"
to = "/podcast/episode/51-was-ist-das-staff-engineer-level"
status = 301
force = true

[[redirects]]
from = "/episodes/52"
to = "/podcast/episode/52-asynchrone-verarbeitung-durch-message-queues-vor-und-nachteile?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep52"
to = "/podcast/episode/52-asynchrone-verarbeitung-durch-message-queues-vor-und-nachteile"
status = 301
force = true

[[redirects]]
from = "/join-discord"
to = "https://discord.gg/WQZG6h85Ep"
status = 302
force = true

[[redirects]]
from = "/fosdem2023"
to = "https://discord.gg/WQZG6h85Ep"
status = 302
force = true

[[redirects]]
from = "/episodes/-1"
to = "/podcast/episode/-1-wrap-up-2022-und-1-geburtstag-learnings-statistiken-und-was-2023-geplant-ist?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep-1"
to = "/podcast/episode/-1-wrap-up-2022-und-1-geburtstag-learnings-statistiken-und-was-2023-geplant-ist"
status = 301
force = true

[[redirects]]
from = "/episodes/53"
to = "/podcast/episode/53-cloud-nocode-ai-chatgpt-ersetzen-unsere-jobs?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep53"
to = "/podcast/episode/53-cloud-nocode-ai-chatgpt-ersetzen-unsere-jobs"
status = 301
force = true

[[redirects]]
from = "/episodes/54"
to = "/podcast/episode/54-key-value-store-redis-einsatzmöglichkeiten-fallstricke-datenstrukturen-hyperloglog-und-flüchtige-persistenz?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep54"
to = "/podcast/episode/54-key-value-store-redis-einsatzmöglichkeiten-fallstricke-datenstrukturen-hyperloglog-und-flüchtige-persistenz"
status = 301
force = true

[[redirects]]
from = "/episodes/55"
to = "/podcast/episode/55-weiterbildung-zertifizierung-newsletter-konferenzen-wie-warum-und-wer-zahlt-das-ganze?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep55"
to = "/podcast/episode/55-weiterbildung-zertifizierung-newsletter-konferenzen-wie-warum-und-wer-zahlt-das-ganze"
status = 301
force = true

[[redirects]]
from = "/episodes/56"
to = "/podcast/episode/56-applikations-skalierung-wann-wieso-was-kostet-es-stateless-und-stateful-horizontal-vs-vertikal?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep56"
to = "/podcast/episode/56-applikations-skalierung-wann-wieso-was-kostet-es-stateless-und-stateful-horizontal-vs-vertikal"
status = 301
force = true

[[redirects]]
from = "/episodes/57"
to = "/podcast/episode/57-servant-leadership-führungsstil-der-neuen-generation?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep57"
to = "/podcast/episode/57-servant-leadership-führungsstil-der-neuen-generation"
status = 301
force = true

[[redirects]]
from = "/episodes/58"
to = "/podcast/episode/58-software-updates-alte-software-long-term-support-und-end-of-life-dates?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep58"
to = "/podcast/episode/58-software-updates-alte-software-long-term-support-und-end-of-life-dates"
status = 301
force = true

[[redirects]]
from = "/episodes/59"
to = "/podcast/episode/59-kann-man-mit-open-source-geld-verdienen?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep59"
to = "/podcast/episode/59-kann-man-mit-open-source-geld-verdienen"
status = 301
force = true

[[redirects]]
from = "/episodes/60"
to = "/podcast/episode/60-on-call-warum-auch-software-engineers-auf-rufbereitschaft-sein-sollten?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/ep60"
to = "/podcast/episode/60-on-call-warum-auch-software-engineers-auf-rufbereitschaft-sein-sollten"
status = 301
force = true

[[redirects]]
from = "/podcast/episode/60-on-call-warum-auch-software-engineers-auf-rufbereitschaft-sollten"
to = "/podcast/episode/60-on-call-warum-auch-software-engineers-auf-rufbereitschaft-sein-sollten"
status = 301
force = true

[[headers]]
for = "/deutsche-tech-podcasts/podcasts.opml"

[headers.values]
Content-Type = "text/x-opml"
Content-Disposition = "attachment"

[build]
publish = "dist/"
command = "astro build"
