name: Astro testing

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '5 1 * * *' # Run nightly
  workflow_dispatch:

jobs:
  astro-testing:
    name: Astro build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.1
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: 20.5.0

      - name: Run make clean
        run: make clean

      - name: Run make init-javascript
        run: make init-javascript

      - name: Run make build
        run: make build
