name: Publish Podcast Episodes

on:
  schedule:
    - cron: '15 5 * * 2' # At 05:15 on Tuesday (UTC) or 6:15am (Winter)/7:15am (Summer) in Vienna but seems that there is a lot of cron traffic, usually it is executed between 7 and 8
  workflow_dispatch:

jobs:
  publishing:
    name: Sync and update podcast episodes
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-python@v5.1.0
        with:
          python-version-file: 'scripts/.python-version'
          cache: 'pip'

      - name: Install python dependencies
        run: make init-python

      - name: Run make update-episode-content
        run: make update-episode-content
        env:
          SPOTIFY_APP_CLIENT_ID: ${{ secrets.SPOTIFY_APP_CLIENT_ID }}
          SPOTIFY_APP_CLIENT_SECRET: ${{ secrets.SPOTIFY_APP_CLIENT_SECRET }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

      - name: Run make update-episode-redirects
        run: make update-episode-redirects

      # Commit results back to repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Synchronisation of Podcast Episodes and redirects
          branch: main
          commit_user_name: Podcast synchronisation workflow bot
          commit_user_email: stehtisch@engineeringkiosk.dev
          commit_author: Podcast synchronisation workflow bot <stehtisch@engineeringkiosk.dev>
